export const FETCH_COUNTRIES_ASIA_REQUEST = "FETCH_COUNTRIES_ASIA_REQUEST"
export const FETCH_COUNTRIES_ASIA_SUCCESS = "FETCH_COUNTRIES_ASIA_SUCCESS"
export const FETCH_COUNTRIES_ASIA_FAILURE = "FETCH_COUNTRIES_ASIA_FAILURE"